spring:
  boot:
    admin:
      client:
        url:
        - http://localhost:8080
  cloud:
    config:
      override-none: true
      allow-override: true
      override-system-properties: false
management:
  endpoints.web.exposure.include: '*'
  endpoint.health.show-details: always
abc: def
