spring:
  boot:
    admin:
      client:
        url:
        - http://localhost:8080
  cloud:
    config:
        allowOverride: true
        overrideNone: true
        overrideSystemProperties: false        
management:
    endpoints.web.exposure.include: '*'
    endpoint.health.show-details: always
abc: def
