spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/matthiaswessel/SpringCloudConfigGit
  boot:
    admin:
      client:
        url:
        - http://localhost:8080
server:
  port: 8081  
management:
    endpoints.web.exposure.include: '*'
    endpoint.health.show-details: always
